# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'Consumser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # pod 'MyFramework', :path => '../MyFramework'
  pod 'MyFramework', :git => 'https://github.com/drvinhhoang/MyFramework.git'

end
